# Generated by Django 2.2.6 on 2019-10-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='texto',
            field=models.TextField(default='type here'),
        ),
    ]
