# Generated by Django 2.2.6 on 2019-10-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20191026_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='texto',
            new_name='content',
        ),
    ]
