# Generated by Django 2.2.6 on 2019-11-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20191105_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images.png', upload_to='post_pics'),
        ),
    ]
