# Generated by Django 2.2.6 on 2019-11-05 16:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile_image',
            new_name='Profiles',
        ),
    ]
