# Generated by Django 2.2.6 on 2019-11-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191105_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='user',
            new_name='uUser',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='image',
        ),
        migrations.AddField(
            model_name='profiles',
            name='Image',
            field=models.ImageField(default='images.png', upload_to='profile_pics'),
        ),
    ]
