# Generated by Django 2.2.6 on 2019-11-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191105_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='uUser',
            new_name='user',
        ),
    ]
