# Generated by Django 2.2.6 on 2019-11-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191106_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='phone',
        ),
    ]
